# Generated by Django 4.2.16 on 2024-11-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                ("cooking_time", models.IntegerField(help_text="Time in minutes")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="recipes/images/"
                    ),
                ),
            ],
        ),
    ]
